name: memory_box
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_svg: ^2.0.17
  freezed_annotation: ^3.0.0
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.3
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
